# Generated by Django 4.2.23 on 2026-02-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direct',
            fields=[
                ('plateid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('plate', models.CharField(blank=True, max_length=60)),
                ('exp_num', models.CharField(blank=True, max_length=30)),
                ('telescope', models.CharField(blank=True, max_length=60)),
                ('observer', models.CharField(blank=True, max_length=60)),
                ('assistant', models.CharField(blank=True, max_length=60)),
                ('object', models.CharField(blank=True, max_length=90)),
                ('ra', models.FloatField(blank=True, db_column='RA', null=True)),
                ('decl', models.FloatField(blank=True, db_column='DECL', null=True)),
                ('date', models.FloatField(blank=True, null=True)),
                ('begin', models.FloatField(blank=True, null=True)),
                ('end', models.FloatField(blank=True, null=True)),
                ('total', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('size', models.CharField(blank=True, max_length=30)),
                ('emulsion', models.CharField(blank=True, max_length=60)),
                ('filter', models.CharField(blank=True, max_length=30)),
                ('seeing', models.FloatField(blank=True, null=True)),
                ('ha_end', models.FloatField(blank=True, db_column='HA_end', null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=300)),
                ('scanned', models.IntegerField(blank=True, null=True)),
                ('num_plates', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=60)),
                ('xls', models.CharField(max_length=150)),
                ('sheet', models.CharField(max_length=60)),
                ('row', models.IntegerField()),
                ('raw_ra', models.CharField(blank=True, db_column='raw_RA', max_length=45)),
                ('raw_dec', models.CharField(blank=True, db_column='raw_DEC', max_length=45)),
                ('raw_date', models.CharField(blank=True, max_length=45)),
                ('raw_size', models.CharField(blank=True, max_length=30)),
                ('raw_ha_end', models.CharField(blank=True, db_column='raw_HA_end', max_length=30)),
                ('raw_seeing', models.CharField(blank=True, max_length=30)),
                ('raw_begin', models.CharField(blank=True, max_length=45)),
                ('raw_end', models.CharField(blank=True, max_length=45)),
                ('coor_source', models.CharField(blank=True, max_length=60)),
                ('temp', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'direct',
            },
        ),
    ]
